services:
  api:
    image: node:23-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"   # API port
      - "9229:9229"   # Debugging port for Node.js
    environment:
      - REDIS_URL=redis://redis:6379
    command: tail -f /dev/null
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
